services:
  mysqldb:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: usermicroservice
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -proot --silent" ]
      interval: 10s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin:5.2.2
    ports:
      - "8079:80"
    environment:
      PMA_HOST: mysqldb
    depends_on:
      - mysqldb

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:8.4
    ports:
      - "8078:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    depends_on:
      postgres:
        condition: service_healthy


  serviceregistry:
    build:
      context: service-registry/
    image: service-registry:1.0.0
    ports:
      - "8761:8761"

#  stockservice:
#    build:
#      context: stock-service/
#    image: stock-service:1.0.0
#    ports:
#      - "8083:8083"
#    depends_on:
#      mysqldb:
#        condition: service_healthy
#      serviceregistry:
#        condition: service_started
#      configserver:
#        condition: service_started

#  userservice:
#    build:
#      context: user-service/
#    image: user-service:1.0.0
#    ports:
#      - "8081:8081"
#    depends_on:
#      mysqldb:
#        condition: service_healthy
#      serviceregistry:
#        condition: service_started
#      configserver:
#        condition: service_started
#
#
#  configserver:
#    build:
#      context: configserver/
#    image: configserver:1.0.0
#    ports:
#      - "8084:8084"
#    environment:
#
#    depends_on:
#      serviceregistry:
#        condition: service_started
#
#  product:
#    build:
#      context: product/
#    image: product-service:1.0.0
#    ports:
#      - "8082:8082"
#    depends_on:
#      postgres:
#        condition: service_healthy
#      serviceregistry:
#        condition: service_started
#      configserver:
#        condition: service_started

#  dashboard-service:
#    build:
#      context: dashboard-service/
#    image: dashboard-service:1.0.0
#    ports:
#      - "8087:8087"
#    depends_on:
#      serviceregistry:
#        condition: service_started
#      configserver:
#        condition: service_started
#
#  apigateway-service:
#    build:
#      context: apigateway-service/
#    image: apigateway-service:1.0.0
#    ports:
#      - "8085:8085"
#    depends_on:
#      serviceregistry:
#        condition: service_started
#      configserver:
#        condition: service_started
