logging:
  level:
    feign: DEBUG
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/productmicroservice
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  application:
    name: PRODUCT-SERVICE

  config:
    import: optional:configserver:http://localhost:8084/

