name: Java CI with Maven

on:
  push:
    branches: [ "dev", "master" ]
    paths:
      - 'apigateway-service/**'
      - 'service-registry/**'
      - 'stock-service/**'
      - 'product/**'
      - 'user-service/**'
  pull_request:
    branches: [ "dev", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ['user-service', 'product', 'stock-service', 'service-registry', 'apigateway-service']

    steps:
      - uses: actions/checkout@v4

      - name: Check if service has a change
        id: changes
        shell: bash
        run: |
          echo "Checking changes for: ${{ matrix.service }}"
          BEFORE_SHA="${{ github.event.before }}"
          if [ -z "$BEFORE_SHA" ]; then
            echo "No 'before' SHA detected — trying to find parent commit..."
            PARENT=$(git rev-parse ${{ github.sha }}^ 2>/dev/null || echo "")
            if [ -n "$PARENT" ]; then
              git diff --name-only $PARENT ${{ github.sha }} | grep "^${{ matrix.service }}/" > changed_files.txt || true
            else
              git show --pretty="" --name-only ${{ github.sha }} | grep "^${{ matrix.service }}/" > changed_files.txt || true
            fi
          else
            git diff --name-only "$BEFORE_SHA" "${{ github.sha }}" | grep "^${{ matrix.service }}/" > changed_files.txt || true
          fi

          if [ -s changed_files.txt ]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Set up JDK 17
        if: steps.changes.outputs.changed == 'true'
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        if: steps.changes.outputs.changed == 'true'
        run: mvn -B package --file ${{ matrix.service }}/pom.xml
