name: Maven Build Affected Modules

on:
  push:
    paths:
      - 'Inventory-Management-System/apigateway-service/**'
      - 'Inventory-Management-System/product/**'
      - 'Inventory-Management-System/service-registry/**'
      - 'Inventory-Management-System/stock-service/**'
      - 'Inventory-Management-System/user-service/**'
      - 'Inventory-Management-System/pom.xml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug directory structure
        run: |
          pwd
          ls -la
          ls -la Inventory-Management-System || echo "Inventory-Management-System not found"

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Determine affected modules
        id: affected
        run: |
          # Detect changed modules based on modified files
          MODULES=$(git diff --name-only HEAD^ HEAD | grep -E 'Inventory-Management-System/(apigateway-service|product|service-registry|stock-service|user-service)' | cut -d'/' -f2 | sort -u | tr '\n' ',' | sed 's/,$//')
          if [[ -z "$MODULES" ]]; then
            echo "No modules affected. Skipping build."
            exit 0
          fi
          echo "Affected modules: $MODULES"
          echo "modules=$MODULES" >> $GITHUB_OUTPUT

      - name: Build with Maven
        if: steps.affected.outputs.modules
        run: |
          # If Inventory-Management-System is not the root, cd into it
          [ -d Inventory-Management-System ] && cd Inventory-Management-System || echo "Already in correct directory"
          mvn -B package -pl "${{ steps.affected.outputs.modules }}" -am --file pom.xml
