
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: STOCK-SERVICE
          uri: lb://STOCK-SERVICE
          predicates:
            - Path=/stocks/**
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product-category/**,/product/**
  config:
    import: optional:configserver:http://localhost:8084/
  security:
    oauth2:
      client:
        registration:
          ims-client:
            client-id: jQB04rdOEVR6wLj4rNjERORqYkA4DSQh
            client-secret: CRpONdA_6XzDCy9XMNYEiMCYo4dtMQ-UnxaqoMO0IbQbbd-A1caBvXo3E_wIfE2P
            provider: auth0
            authorization-grant-type: authorization_code
            scope: openid,profile,email,offline_access

        provider:
          auth0:
            issuer-uri: https://dev-tifsgpj0de6wps8x.au.auth0.com/
      resourceserver:
        jwt:
          issuer-uri: https://dev-tifsgpj0de6wps8x.au.auth0.com/
          jwk-set-uri: https://dev-tifsgpj0de6wps8x.au.auth0.com/.well-known/jwks.json
          audiences: https://ims-api

server:
  port: 8085

logging:
  level:
    org.springframework.security: DEBUG

app:
  oauth2:
    login-success-url: http://localhost:8085/auth/login

